/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.gov.mef.opendata.webformassistenza.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import it.gov.mef.opendata.webformassistenza.model.AssitenzaNoipa;
import it.gov.mef.opendata.webformassistenza.model.AssitenzaNoipaModel;
import it.gov.mef.opendata.webformassistenza.model.AssitenzaNoipaSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the AssitenzaNoipa service. Represents a row in the &quot;AssitenzaNoipa&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link AssitenzaNoipaModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AssitenzaNoipaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AssitenzaNoipaImpl
 * @see AssitenzaNoipa
 * @see AssitenzaNoipaModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class AssitenzaNoipaModelImpl extends BaseModelImpl<AssitenzaNoipa>
	implements AssitenzaNoipaModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a AssitenzaNoipa model instance should use the {@link AssitenzaNoipa} interface instead.
	 */
	public static final String TABLE_NAME = "AssitenzaNoipa";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "assistenzaId", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("assistenzaId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table AssitenzaNoipa (uuid_ VARCHAR(75) null,assistenzaId LONG not null primary key)";
	public static final String TABLE_SQL_DROP = "drop table AssitenzaNoipa";
	public static final String ORDER_BY_JPQL = " ORDER BY assitenzaNoipa.assistenzaId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY AssitenzaNoipa.assistenzaId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(it.gov.mef.opendata.webformassistenza.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.it.gov.mef.opendata.webformassistenza.model.AssitenzaNoipa"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(it.gov.mef.opendata.webformassistenza.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.it.gov.mef.opendata.webformassistenza.model.AssitenzaNoipa"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(it.gov.mef.opendata.webformassistenza.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.it.gov.mef.opendata.webformassistenza.model.AssitenzaNoipa"),
			true);
	public static final long UUID_COLUMN_BITMASK = 1L;
	public static final long ASSISTENZAID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static AssitenzaNoipa toModel(AssitenzaNoipaSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		AssitenzaNoipa model = new AssitenzaNoipaImpl();

		model.setUuid(soapModel.getUuid());
		model.setAssistenzaId(soapModel.getAssistenzaId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<AssitenzaNoipa> toModels(AssitenzaNoipaSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<AssitenzaNoipa> models = new ArrayList<AssitenzaNoipa>(soapModels.length);

		for (AssitenzaNoipaSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(it.gov.mef.opendata.webformassistenza.service.util.ServiceProps.get(
				"lock.expiration.time.it.gov.mef.opendata.webformassistenza.model.AssitenzaNoipa"));

	public AssitenzaNoipaModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _assistenzaId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAssistenzaId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _assistenzaId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AssitenzaNoipa.class;
	}

	@Override
	public String getModelClassName() {
		return AssitenzaNoipa.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("assistenzaId", getAssistenzaId());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long assistenzaId = (Long)attributes.get("assistenzaId");

		if (assistenzaId != null) {
			setAssistenzaId(assistenzaId);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getAssistenzaId() {
		return _assistenzaId;
	}

	@Override
	public void setAssistenzaId(long assistenzaId) {
		_columnBitmask = -1L;

		_assistenzaId = assistenzaId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			AssitenzaNoipa.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AssitenzaNoipa toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (AssitenzaNoipa)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AssitenzaNoipaImpl assitenzaNoipaImpl = new AssitenzaNoipaImpl();

		assitenzaNoipaImpl.setUuid(getUuid());
		assitenzaNoipaImpl.setAssistenzaId(getAssistenzaId());

		assitenzaNoipaImpl.resetOriginalValues();

		return assitenzaNoipaImpl;
	}

	@Override
	public int compareTo(AssitenzaNoipa assitenzaNoipa) {
		int value = 0;

		if (getAssistenzaId() < assitenzaNoipa.getAssistenzaId()) {
			value = -1;
		}
		else if (getAssistenzaId() > assitenzaNoipa.getAssistenzaId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof AssitenzaNoipa)) {
			return false;
		}

		AssitenzaNoipa assitenzaNoipa = (AssitenzaNoipa)obj;

		long primaryKey = assitenzaNoipa.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		AssitenzaNoipaModelImpl assitenzaNoipaModelImpl = this;

		assitenzaNoipaModelImpl._originalUuid = assitenzaNoipaModelImpl._uuid;

		assitenzaNoipaModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<AssitenzaNoipa> toCacheModel() {
		AssitenzaNoipaCacheModel assitenzaNoipaCacheModel = new AssitenzaNoipaCacheModel();

		assitenzaNoipaCacheModel.uuid = getUuid();

		String uuid = assitenzaNoipaCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			assitenzaNoipaCacheModel.uuid = null;
		}

		assitenzaNoipaCacheModel.assistenzaId = getAssistenzaId();

		return assitenzaNoipaCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", assistenzaId=");
		sb.append(getAssistenzaId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("it.gov.mef.opendata.webformassistenza.model.AssitenzaNoipa");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>assistenzaId</column-name><column-value><![CDATA[");
		sb.append(getAssistenzaId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = AssitenzaNoipa.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			AssitenzaNoipa.class, ModelWrapper.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _assistenzaId;
	private long _columnBitmask;
	private AssitenzaNoipa _escapedModel;
}