/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.gov.mef.opendata.webformassistenza.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the EntiAmministrazione service. Represents a row in the &quot;EntiAmministrazione&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.gov.mef.opendata.webformassistenza.model.impl.EntiAmministrazioneModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.gov.mef.opendata.webformassistenza.model.impl.EntiAmministrazioneImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EntiAmministrazione
 * @see it.gov.mef.opendata.webformassistenza.model.impl.EntiAmministrazioneImpl
 * @see it.gov.mef.opendata.webformassistenza.model.impl.EntiAmministrazioneModelImpl
 * @generated
 */
@ProviderType
public interface EntiAmministrazioneModel extends BaseModel<EntiAmministrazione> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a EntiAmministrazione model instance should use the {@link EntiAmministrazione} interface instead.
	 */

	/**
	 * Returns the primary key of this EntiAmministrazione.
	 *
	 * @return the primary key of this EntiAmministrazione
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this EntiAmministrazione.
	 *
	 * @param primaryKey the primary key of this EntiAmministrazione
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this EntiAmministrazione.
	 *
	 * @return the uuid of this EntiAmministrazione
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this EntiAmministrazione.
	 *
	 * @param uuid the uuid of this EntiAmministrazione
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the enti ID of this EntiAmministrazione.
	 *
	 * @return the enti ID of this EntiAmministrazione
	 */
	public long getEntiId();

	/**
	 * Sets the enti ID of this EntiAmministrazione.
	 *
	 * @param entiId the enti ID of this EntiAmministrazione
	 */
	public void setEntiId(long entiId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(EntiAmministrazione entiAmministrazione);

	@Override
	public int hashCode();

	@Override
	public CacheModel<EntiAmministrazione> toCacheModel();

	@Override
	public EntiAmministrazione toEscapedModel();

	@Override
	public EntiAmministrazione toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}