/**
- * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.gov.mef.opendata.webformassistenza.service.impl;

import java.util.HashMap;
import java.util.Map;

import it.gov.mef.opendata.webformassistenza.service.base.EntiAmministrazioneLocalServiceBaseImpl;

// TODO: Auto-generated Javadoc
/**
 * The implementation of the EntiAmministrazione local service.
 *
 * <p>
 * All custom service methods should be put in this class. Whenever methods are
 * added, rerun ServiceBuilder to copy their definitions into the
 * {@link it.gov.mef.opendata.webformassistenza.service.EntiAmministrazioneLocalService}
 * interface.
 *
 * <p>
 * This is a local service. Methods of this service will not have security
 * checks based on the propagated JAAS credentials because this service can only
 * be accessed from within the same VM.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EntiAmministrazioneLocalServiceBaseImpl
 * @see it.gov.mef.opendata.webformassistenza.service.EntiAmministrazioneLocalServiceUtil
 */
public class EntiAmministrazioneLocalServiceImpl extends EntiAmministrazioneLocalServiceBaseImpl {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never reference this class directly. Always use {@link
	 * it.gov.mef.opendata.webformassistenza.service.
	 * EntiAmministrazioneLocalServiceUtil} to access the EntiAmministrazione local
	 * service.
	 */

	/* (non-Javadoc)
	 * @see it.gov.mef.opendata.webformassistenza.service.EntiAmministrazioneLocalService#getEnti()
	 */
	public  Map<String,String> getEnti(){
		Map<String,String> enti = new HashMap<String,String>();
		
		/** metodo spezzettato per controlli sonar **/
		enti1(enti);
		enti2(enti);
		enti3(enti);
		enti4(enti);
		enti5(enti);

		return enti;
		
	}

	private void enti5(Map<String, String> enti) {
		enti.put("|2 - MIN.INFRASTRUTTURE E TRASPORTI","MIN.INFRASTRUTTURE E TRASPORTI");
		enti.put("|7 - MINISTERO DEGLI AFFARI ESTERI","MINISTERO DEGLI AFFARI ESTERI");
		enti.put("|8 - MINISTERO DEL LAVORO E DELLE POLITICHE SOCIALI","MINISTERO DEL LAVORO E DELLE POLITICHE SOCIALI");
		enti.put("|3 - MINISTERO DELLA DIFESA","MINISTERO DELLA DIFESA");
		enti.put("|1415 - MINISTERO DELLA DIFESA - COMANDO GENERALE ARMA CARABINIERI","MINISTERO DELLA DIFESA - COMANDO GENERALE ARMA CARABINIERI");
		enti.put("|1414 - MINISTERO DELLA DIFESA - F.A.","MINISTERO DELLA DIFESA - F.A.");
		enti.put("|9 - MINISTERO DELLA GIUSTIZIA","MINISTERO DELLA GIUSTIZIA");
		enti.put("|10 - MINISTERO DELLA SALUTE","MINISTERO DELLA SALUTE");
		enti.put("|6 - MINISTERO DELL'AMBIENTE E TUTELA DEL TERRITORIO E DEL MARE","MINISTERO DELL'AMBIENTE E TUTELA DEL TERRITORIO E DEL MARE");
		enti.put("|11 - MINISTERO DELLE  POLITICHE AGRICOLE,  ALIMENTARI E FORESTALI","MINISTERO DELLE  POLITICHE AGRICOLE,  ALIMENTARI E FORESTALI");
		enti.put("|1 - MINISTERO DELL'ECONOMIA E FINANZE","MINISTERO DELL'ECONOMIA E FINANZE");
		enti.put("|12 - MINISTERO DELL'INTERNO","MINISTERO DELL'INTERNO");
		enti.put("|2020 - MINISTERO DELL'INTERNO - DIPARTIMENTO DELLA P.S.","MINISTERO DELL'INTERNO - DIPARTIMENTO DELLA P.S.");
		enti.put("|4 - MINISTERO DELL'ISTRUZIONE, UNIVERSITA' E RICERCA - EX  MPI","MINISTERO DELL'ISTRUZIONE, UNIVERSITA' E RICERCA - EX  MPI");
		enti.put("|13 - MINISTERO DELLO SVILUPPO ECONOMICO","MINISTERO DELLO SVILUPPO ECONOMICO");
		enti.put("|3030 - MINISTERO INFRASTRUTTURE E TRASPORTI - CAPITANERIE DI PORTO","MINISTERO INFRASTRUTTURE E TRASPORTI - CAPITANERIE DI PORTO");
		enti.put("|14 - MINISTERO PER I BENI E LE ATTIVITA' CULTURALI","MINISTERO PER I BENI E LE ATTIVITA' CULTURALI");
		enti.put("|893 - ORDINE DEGLI ASSISTENTI SOCIALI DELLA REGIONE ABRUZZO","ORDINE DEGLI ASSISTENTI SOCIALI DELLA REGIONE ABRUZZO");
		enti.put("|957 - ORDINE DOTT. COMMERCIALISTI ED ESPERTI CONTABILI DI VERONA","ORDINE DOTT. COMMERCIALISTI ED ESPERTI CONTABILI DI VERONA");
		enti.put("|5 - PRESIDENZA DEL CONSIGLIO DEI MINISTRI","PRESIDENZA DEL CONSIGLIO DEI MINISTRI");
		enti.put("|822 - REGIONE LAZIO ","REGIONE LAZIO ");
		enti.put("|43 - SCUOLA NAZIONALE DELL'AMMINISTRAZIONE","SCUOLA NAZIONALE DELL'AMMINISTRAZIONE");
		enti.put("|947 - STAZIONE ZOOLOGICA ANTON DOHRN","STAZIONE ZOOLOGICA ANTON DOHRN");
		enti.put("|839 - UNIONE CAMPOSPINOSO ALBAREDO","UNIONE CAMPOSPINOSO ALBAREDO");
		enti.put("|865 - UNIONE DEI COMUNI DELLA VALCONCA","UNIONE DEI COMUNI DELLA VALCONCA");
	}

	private void enti4(Map<String, String> enti) {
		enti.put("|17 - CONSIGLIO DI STATO  E  T. A. R.","CONSIGLIO DI STATO  E  T. A. R.");
		enti.put("|28 - CONSIGLIO PER RIC. IN AGRICOLTURA E ANALISI ECONOMIA AGRARIA","CONSIGLIO PER RIC. IN AGRICOLTURA E ANALISI ECONOMIA AGRARIA");
		enti.put("|33 - CORPO FORESTALE DELLO STATO","CORPO FORESTALE DELLO STATO");
		enti.put("|18 - CORTE DEI CONTI","CORTE DEI CONTI");
		enti.put("|962 - E.N.A.C.","E.N.A.C.");
		enti.put("|807 - ENTE DI GESTIONE PER I PARCHI E LA BIODIVERSITA DELTA DEL PO","ENTE DI GESTIONE PER I PARCHI E LA BIODIVERSITA DELTA DEL PO");
		enti.put("|36 - ENTE NAZIONALE CELLULOSA E CARTA","ENTE NAZIONALE CELLULOSA E CARTA");
		enti.put("|943 - ENTE PARCO NAZ. DELL'APPENNINO LUCANO VAL D'AGRI LAGONEGRESE","ENTE PARCO NAZ. DELL'APPENNINO LUCANO VAL D'AGRI LAGONEGRESE");
		enti.put("|937 - ENTE PARCO NAZIONALE DEL CILENTO, VALLO DI DIANO E ALBURNI","ENTE PARCO NAZIONALE DEL CILENTO, VALLO DI DIANO E ALBURNI");
		enti.put("|945 - ENTE PARCO NAZIONALE DEL GRAN SASSO E MONTI DELLA LAGA","ENTE PARCO NAZIONALE DEL GRAN SASSO E MONTI DELLA LAGA");
		enti.put("|938 - ENTE PARCO NAZIONALE DELLA MAJELLA","ENTE PARCO NAZIONALE DELLA MAJELLA");
		enti.put("|898 - ENTE STRUMENTALE ALLA CROCE ROSSA ITALIANA","ENTE STRUMENTALE ALLA CROCE ROSSA ITALIANA");
		enti.put("|885 - FONDAZIONE EMILIA MUNER DE GIUDICI","FONDAZIONE EMILIA MUNER DE GIUDICI");
		enti.put("|1717 - GUARDIA DI FINANZA","GUARDIA DI FINANZA");
		enti.put("SANITA|904 - IFO - ISTITUTI FISIOTERAPICI OSPITALIERI","IFO - ISTITUTI FISIOTERAPICI OSPITALIERI");
		enti.put("|888 - INAF-ISTITUTO NAZIONALE ASTROFISICA","INAF-ISTITUTO NAZIONALE ASTROFISICA");
		enti.put("SANITA|906 - I.N.M.I. L.SPALLANZANI IRCCS","I.N.M.I. L.SPALLANZANI IRCCS");
		enti.put("|31 - INVALSI","INVALSI");
		enti.put("|944 - I.P.A.B. S.ANTONIO ABATE TRINO","I.P.A.B. S.ANTONIO ABATE TRINO");
		enti.put("|954 - ISPETTORATO NAZIONALE DEL LAVORO","ISPETTORATO NAZIONALE DEL LAVORO");
		enti.put("|889 - ISPRA","ISPRA");
		enti.put("|949 - ISTAT","ISTAT");
		enti.put("|29 - ISTITUTO AGRONOMICO PER L'OLTREMARE","ISTITUTO AGRONOMICO PER L'OLTREMARE");
		enti.put("|32 - ISTITUTO SUPERIORE DI SANITA'","ISTITUTO SUPERIORE DI SANITA'");
	}

	private void enti3(Map<String, String> enti) {
		enti.put("|16 - C.N.E.L.- CONSIGLIO  NAZIONALE DELL'ECONOMIA E DEL LAVORO","C.N.E.L.- CONSIGLIO  NAZIONALE DELL'ECONOMIA E DEL LAVORO");
		enti.put("|841 - COMUNE DI ALBAREDO ARNABOLDI","COMUNE DI ALBAREDO ARNABOLDI");
		enti.put("|830 - COMUNE DI ALEZIO","COMUNE DI ALEZIO");
		enti.put("|835 - COMUNE DI AZZANO MELLA","COMUNE DI AZZANO MELLA");
		enti.put("|833 - COMUNE DI BORGONOVO VAL TIDONE ","COMUNE DI BORGONOVO VAL TIDONE ");
		enti.put("|836 - COMUNE DI BOVEZZO","COMUNE DI BOVEZZO");
		enti.put("|850 - COMUNE DI BREBBIA","COMUNE DI BREBBIA");
		enti.put("|876 - COMUNE DI BULCIAGO","COMUNE DI BULCIAGO");
		enti.put("|812 - COMUNE DI CAMPI SALENTINA","COMUNE DI CAMPI SALENTINA");
		enti.put("|840 - COMUNE DI CAMPOSPINOSO","COMUNE DI CAMPOSPINOSO");
		enti.put("|837 - COMUNE DI CANDA","COMUNE DI CANDA");
		enti.put("|890 - COMUNE DI CARLINO","COMUNE DI CARLINO");
		enti.put("|816 - COMUNE DI CAROSINO","COMUNE DI CAROSINO");
		enti.put("|811 - COMUNE DI CASALE CORTE CERRO","COMUNE DI CASALE CORTE CERRO");
		enti.put("|860 - COMUNE DI CASTELLO DELL'ACQUA","COMUNE DI CASTELLO DELL'ACQUA");
		enti.put("|842 - COMUNE DI CASTELVERDE","COMUNE DI CASTELVERDE");
		enti.put("|823 - COMUNE DI CERRO AL LAMBRO","COMUNE DI CERRO AL LAMBRO");
		enti.put("|808 - COMUNE DI CHIOPRIS-VISCONE","COMUNE DI CHIOPRIS-VISCONE");
		enti.put("|813 - COMUNE DI CODOGNE'","COMUNE DI CODOGNE'");
		enti.put("|824 - COMUNE DI CONA","COMUNE DI CONA");
		enti.put("|838 - COMUNE DI CORIANO","COMUNE DI CORIANO");
		enti.put("|831 - COMUNE DI CORLETO MONFORTE","COMUNE DI CORLETO MONFORTE");
		enti.put("|818 - COMUNE DI COSIO VALTELLINO","COMUNE DI COSIO VALTELLINO");
		enti.put("|815 - COMUNE DI DIANO SAN PIETRO","COMUNE DI DIANO SAN PIETRO");
		enti.put("|804 - COMUNE DI DORIO","COMUNE DI DORIO");
		enti.put("|886 - COMUNE DI FROSINONE","COMUNE DI FROSINONE");
		enti.put("|814 - COMUNE DI FUSINE","COMUNE DI FUSINE");
		enti.put("|887 - COMUNE DI GIARRE","COMUNE DI GIARRE");
		enti.put("|817 - COMUNE DI LEINI","COMUNE DI LEINI");
		enti.put("|821 - COMUNE DI LIPOMO","COMUNE DI LIPOMO");
		enti.put("|848 - COMUNE DI LOCERI","COMUNE DI LOCERI");
		enti.put("|862 - COMUNE DI LOCOROTONDO","COMUNE DI LOCOROTONDO");
		enti.put("|846 - COMUNE DI MARANO LAGUNARE","COMUNE DI MARANO LAGUNARE");
		enti.put("|829 - COMUNE DI MERCATO SAN SEVERINO","COMUNE DI MERCATO SAN SEVERINO");
		enti.put("|845 - COMUNE DI MONDAINO","COMUNE DI MONDAINO");
		enti.put("|859 - COMUNE DI MONTEGRIDOLFO ","COMUNE DI MONTEGRIDOLFO ");
		enti.put("|819 - COMUNE DI MONTEIASI ","COMUNE DI MONTEIASI ");
		enti.put("|826 - COMUNE DI MONTEMESOLA ","COMUNE DI MONTEMESOLA ");
		enti.put("|866 - COMUNE DI MONTESCUDO","COMUNE DI MONTESCUDO");
		enti.put("|834 - COMUNE DI MONTORFANO","COMUNE DI MONTORFANO");
		enti.put("|820 - COMUNE DI MOTTOLA","COMUNE DI MOTTOLA");
		enti.put("|825 - COMUNE DI OLGINATE","COMUNE DI OLGINATE");
		enti.put("|827 - COMUNE DI PALAGIANELLO","COMUNE DI PALAGIANELLO");
		enti.put("|806 - COMUNE DI PALMANOVA","COMUNE DI PALMANOVA");
		enti.put("|956 - COMUNE DI PELLEZZANO","COMUNE DI PELLEZZANO");
		enti.put("|832 - COMUNE DI PESCATE","COMUNE DI PESCATE");
		enti.put("|810 - COMUNE DI PIANA DEGLI ALBANESI","COMUNE DI PIANA DEGLI ALBANESI");
		enti.put("|863 - COMUNE DI SALUDECIO","COMUNE DI SALUDECIO");
		enti.put("|903 - COMUNE DI SAN GIOVANNI IN MARIGNANO","COMUNE DI SAN GIOVANNI IN MARIGNANO");
		enti.put("|946 - COMUNE DI SANT'EUFEMIA D'ASPROMONTE","COMUNE DI SANT'EUFEMIA D'ASPROMONTE");
		enti.put("|847 - COMUNE DI SEDINI","COMUNE DI SEDINI");
		enti.put("|809 - COMUNE DI TROFARELLO","COMUNE DI TROFARELLO");
		enti.put("|913 - COMUNE DI TRUCCAZZANO","COMUNE DI TRUCCAZZANO");
		enti.put("|828 - COMUNE DI VALGREGHENTINO","COMUNE DI VALGREGHENTINO");
		enti.put("|918 - COMUNE DI ZECCONE ","COMUNE DI ZECCONE ");
	}

	private void enti2(Map<String, String> enti) {
		enti.put("|897 - A.S.P.CASA DI RIPOSO GIUSEPPE SIRCH","A.S.P.CASA DI RIPOSO GIUSEPPE SIRCH");
		enti.put("|803 - AUTORITA' DI BACINO DEI FIUMI DELL'ALTO ADRIATICO","AUTORITA' DI BACINO DEI FIUMI DELL'ALTO ADRIATICO");
		enti.put("|801 - AUTORITA' DI BACINO DEL FIUME ADIGE","AUTORITA' DI BACINO DEL FIUME ADIGE");
		enti.put("|872 - AUTORITA' DI BACINO DEL FIUME ARNO","AUTORITA' DI BACINO DEL FIUME ARNO");
		enti.put("|861 - AUTORITA' DI BACINO DEL FIUME PO","AUTORITA' DI BACINO DEL FIUME PO");
		enti.put("|960 - AUTORITA' DI BACINO DISTR. DELL'APPENNINO SETTENTRIONALE","AUTORITA' DI BACINO DISTR. DELL'APPENNINO SETTENTRIONALE");
		enti.put("|963 - AUTORITA' DI BACINO DISTRETTUALE APPENNINO MERIDIONALE","AUTORITA' DI BACINO DISTRETTUALE APPENNINO MERIDIONALE");
		enti.put("|959 - AUTORITA' DI BACINO DISTRETTUALE DEL FIUME PO","AUTORITA' DI BACINO DISTRETTUALE DEL FIUME PO");
		enti.put("|958 - AUTORITA' DI BACINO DISTRETTUALE DELL'APPENNINO CENTRALE","AUTORITA' DI BACINO DISTRETTUALE DELL'APPENNINO CENTRALE");
		enti.put("|961 - AUTORITA' DI BACINO DISTRETTUALE DELLE ALPI ORIENTALI","AUTORITA' DI BACINO DISTRETTUALE DELLE ALPI ORIENTALI");
		enti.put("|873 - AUTORITA' DI BACINO FIUME TEVERE","AUTORITA' DI BACINO FIUME TEVERE");
		enti.put("|919 - AUTORITA' UFFICIO PARLAMENTARE DI BILANCIO (UPB)","AUTORITA' UFFICIO PARLAMENTARE DI BILANCIO (UPB)");
		enti.put("|15 - AVVOCATURA GENERALE DELLO STATO ","AVVOCATURA GENERALE DELLO STATO ");
		enti.put("SANITA|948 - AZIENDA OSPEDALIERA DI RILIEVO NAZIONALE \"a.cardarelli\"","  AZIENDA OSPEDALIERA DI RILIEVO NAZIONALE \"A.CARDARELLI\" ");
		enti.put("SANITA|907 - AZIENDA OSPEDALIERA SAN CAMILLO FORLANINI","AZIENDA OSPEDALIERA SAN CAMILLO FORLANINI");
		enti.put("SANITA|921 - AZIENDA OSPEDALIERA SAN GIOVANNI ADDOLORATA","AZIENDA OSPEDALIERA SAN GIOVANNI ADDOLORATA");
		enti.put("SANITA|905 - AZIENDA REGIONALE EMERGENZA SANITARIA - ARES118","AZIENDA REGIONALE EMERGENZA SANITARIA - ARES118");
		enti.put("SANITA|924 - AZIENDA SANITARIA LOCALE FROSINONE","AZIENDA SANITARIA LOCALE FROSINONE");
		enti.put("SANITA|923 - AZIENDA SANITARIA LOCALE ROMA B","AZIENDA SANITARIA LOCALE ROMA B");
		enti.put("SANITA|909 - AZIENDA SANITARIA LOCALE ROMA C","AZIENDA SANITARIA LOCALE ROMA C");
		enti.put("SANITA|915 - AZIENDA SANITARIA LOCALE ROMA E","AZIENDA SANITARIA LOCALE ROMA E");
		enti.put("SANITA|930 - AZIENDA UNITA' SANITARIA LOCALE LATINA","AZIENDA UNITA' SANITARIA LOCALE LATINA");
		enti.put("SANITA|917 - AZIENDA UNITA' SANITARIA LOCALE RIETI","AZIENDA UNITA' SANITARIA LOCALE RIETI");
		enti.put("SANITA|929 - AZIENDA UNITA' SANITARIA LOCALE VITERBO","AZIENDA UNITA' SANITARIA LOCALE VITERBO");
	}

	private void enti1(Map<String, String> enti) {
		enti.put("|20 - AGENZIA DEL TERRITORIO","AGENZIA DEL TERRITORIO");
		enti.put("|21 - AGENZIA DELLE DOGANE","AGENZIA DELLE DOGANE");
		enti.put("|22 - AGENZIA DELLE ENTRATE","AGENZIA DELLE ENTRATE");
		enti.put("|867 - AGENZIA ITALIANA DEL FARMACO - AIFA","AGENZIA ITALIANA DEL FARMACO - AIFA");
		enti.put("|950 - AGENZIA ITALIANA PER LA COOPERAZIONE ALLO SVILUPPO","AGENZIA ITALIANA PER LA COOPERAZIONE ALLO SVILUPPO");
		enti.put("|27 - AGENZIA NAZIONALE PER I GIOVANI - ANG","AGENZIA NAZIONALE PER I GIOVANI - ANG");
		enti.put("|805 - AGENZIA NAZIONALE PER LA SICUREZZA DEL VOLO","AGENZIA NAZIONALE PER LA SICUREZZA DEL VOLO");
		enti.put("|849 - AGENZIA PER LA COESIONE TERRITORIALE","AGENZIA PER LA COESIONE TERRITORIALE");
		enti.put("|23 - AGENZIA PER LE EROGAZIONI IN AGRICOLTURA","AGENZIA PER LE EROGAZIONI IN AGRICOLTURA");
		enti.put("|4056 - AGENZIA PER L'ITALIA DIGITALE","AGENZIA PER L'ITALIA DIGITALE");
		enti.put("|0 - ALTRO","ALTRO");
		enti.put("|900 - AMMINISTRAZIONE PROVINCIALE DI IMPERIA","AMMINISTRAZIONE PROVINCIALE DI IMPERIA");
		enti.put("|868 - ANBSC-AGENZIA NAZIONALE BENI SEQUESTRATI E CONFISCATI","ANBSC-AGENZIA NAZIONALE BENI SEQUESTRATI E CONFISCATI");
		enti.put("|953 - ANPAL - AGENZIA NAZIONALE PER LE POLITICHE ATTIVE DEL LAVORO","ANPAL - AGENZIA NAZIONALE PER LE POLITICHE ATTIVE DEL LAVORO");
		enti.put("|932 - ANSF - AGENZIA NAZIONALE PER LA SICUREZZA DELLE FERROVIE","ANSF - AGENZIA NAZIONALE PER LA SICUREZZA DELLE FERROVIE");
		enti.put("|843 - ANVUR(AGENZIA NAZ.VALUTAZIONE SIST.UNIVERSITARIO E RICERCA)","ANVUR(AGENZIA NAZ.VALUTAZIONE SIST.UNIVERSITARIO E RICERCA)");
		enti.put("|802 - ARAN","ARAN");
		enti.put("|25 - ARCHIVI NOTARILI","ARCHIVI NOTARILI");
		enti.put("|871 - ARRS-AGENZIA REGIONALE RELAZIONI SINDACALI VAL D'AOSTA","ARRS-AGENZIA REGIONALE RELAZIONI SINDACALI VAL D'AOSTA");
		enti.put("|920 - ARSIAL-AG. REG.LE SVILUPPO E INNOV. AGRICOLTURA DEL LAZIO","ARSIAL-AG. REG.LE SVILUPPO E INNOV. AGRICOLTURA DEL LAZIO");
		enti.put("SANITA|914 - ASL ROMA 3","ASL ROMA 3");
		enti.put("SANITA|926 - ASL ROMA 4","ASL ROMA 4");
		enti.put("SANITA|916 - ASL ROMA 5","ASL ROMA 5");
		enti.put("SANITA|910 - ASL ROMA 6","ASL ROMA 6");
	}

}